version: '3.9'

services:
  mongodb:
#     container_name: mymongo
#     build:
#         dockerfile: Dockerfile
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - db:/apps/mongo:/data/db
#       - ./keys/mongo-replica-set.key:/data/db/mongo-replica-set.key
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=items_db
#     command:
#       - "--replSet"
#       - "dbrs"
#       - "--keyFile"
#       - "/data/db/mongo-replica-set.key"
#     entrypoint:
#       - bash
#       - -c
#       - chmod 400 replica.key
#         chown 999:999 replica.key
#         exec docker-entrypoint.sh $$@
#     command: ["--replSet", "dbrs", "--bind_ip_all", "--keyFile", "replica.key"]
#     command: ["mongod", "--bind_ip_all", "--replSet", "replicaSet01", "--keyFile", "replica.key"]
#     healthcheck:
#         test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u mongo -p mongo --quiet) -eq 1
#         interval: 10s
#         start_period: 30s
#     command: ["--replSet", "dbrs", "--bind_ip_all"]
    networks:
      - crm-network
volumes:
  db:
    driver: local
networks:
  crm-network:
    driver: bridge